version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EZK3
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql
      - ./mydatabase.sql:/docker-entrypoint-initdb.d/mydatabase.sql
volumes:
  db_data:
